package execution

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"github.com/shopspring/decimal"
)

type StrategyTotals struct {
	Fees    decimal.Decimal
	Funding decimal.Decimal
}

// LotEntryTime is the latest committed fill in the lot's entry direction.
// Legacy genesis with no typed fills returns zero for the caller's explicit
// source timestamp fallback. Reads are scoped by strategy/lot, not all events.
func (s *Store) LotEntryTime(ctx context.Context, strategy StrategyID, lot VirtualLotID, entrySide OrderSide) (int64, error) {
	if !canonicalID(string(strategy)) || !canonicalID(string(lot)) || entrySide != Buy && entrySide != Sell {
		return 0, errors.New("execution: invalid lot entry timestamp scope")
	}
	operation := opReadLotEntryBuy
	if entrySide == Sell {
		operation = opReadLotEntrySell
	}
	var atMS int64
	err := s.readRecord(ctx, func(tx *storeTxn) error {
		return tx.QueryRow(operation, s.accountID, string(strategy), string(lot)).Scan(&atMS)
	})
	return atMS, err
}

// LotEntrySteps derives total committed entry quantity from fill postings.
// Imported genesis is separate and supplied by its immutable source evidence.
func (s *Store) LotEntrySteps(ctx context.Context, strategy StrategyID, lot VirtualLotID, entrySide OrderSide) (int64, error) {
	if !canonicalID(string(strategy)) || !canonicalID(string(lot)) || entrySide != Buy && entrySide != Sell {
		return 0, errors.New("execution: invalid lot entry quantity scope")
	}
	operation := opReadLotEntryStepsBuy
	if entrySide == Sell {
		operation = opReadLotEntryStepsSell
	}
	var steps int64
	err := s.readRecord(ctx, func(tx *storeTxn) error {
		return tx.QueryRow(operation, s.accountID, string(strategy), string(lot)).Scan(&steps)
	})
	return steps, err
}

// StrategyCheckpoint is committed with the local plan that accepts its requests.
type StrategyCheckpoint struct {
	Strategy StrategyID
	Name     string
	Payload  json.RawMessage
	Events   []StrategyAcceptedEvent
	// Records are point-readable metadata committed with the same plan. They
	// belong to this checkpoint's strategy and cannot contain records or events.
	Records []StrategyCheckpoint
}

// StrategyAcceptedEvent precedes any fill generated by accepting the command.
// CommandID is stable across retries; no legacy projection identity is needed.
type StrategyAcceptedEvent struct {
	Strategy  StrategyID
	Lot       VirtualLotID
	Kind      IntentKind
	CommandID string
	AtMS      int64
}

func (s *Store) saveAcceptedCheckpoint(ctx context.Context, checkpoint StrategyCheckpoint) error {
	seen := map[string]bool{checkpoint.Name: true}
	for _, record := range checkpoint.Records {
		if record.Strategy != checkpoint.Strategy || len(record.Records) != 0 || len(record.Events) != 0 || seen[record.Name] {
			return errors.New("execution: invalid checkpoint metadata batch")
		}
		seen[record.Name] = true
	}
	return s.atomically(ctx, func(ctx context.Context) error {
		for _, record := range checkpoint.Records {
			if err := s.SaveStrategyCheckpoint(ctx, record.Strategy, record.Name, record.Payload); err != nil {
				return err
			}
		}
		if err := s.SaveStrategyCheckpoint(ctx, checkpoint.Strategy, checkpoint.Name, checkpoint.Payload); err != nil {
			return err
		}
		return s.commit(ctx, func(tx *storeTxn) error {
			for _, event := range checkpoint.Events {
				if !canonicalID(string(event.Strategy)) || !canonicalID(string(event.Lot)) || !canonicalID(event.CommandID) || event.AtMS < 0 || event.Kind != EntryIntent && event.Kind != ExitIntent {
					return errors.New("execution: invalid strategy acceptance event")
				}
				body, err := payload(event)
				if err != nil {
					return err
				}
				id := "accepted-" + rebalanceID(event.Strategy, "/", event.Lot, "/", event.Kind, "/", event.CommandID)
				legacyID := "accepted-" + legacyRebalanceID(event.Strategy, "/", event.Lot, "/", event.Kind, "/", event.CommandID)
				var previousKind, previousBody string
				if err := tx.QueryRow(opReadEvent, s.accountID, legacyID).Scan(&previousKind, &previousBody); err == nil {
					// An equal old fact is a retry. A colliding old tuple with a
					// different body belongs to its own new framed namespace.
					if previousKind == "StrategyAccepted" {
						var previous StrategyAcceptedEvent
						if err := json.Unmarshal([]byte(previousBody), &previous); err != nil {
							return err
						}
						if previous.Strategy == event.Strategy && previous.Lot == event.Lot && previous.Kind == event.Kind && previous.CommandID == event.CommandID {
							if previousBody != body {
								return errors.New("execution: legacy acceptance identity reused with different fact")
							}
							id = legacyID
						}
					}
				} else if !errors.Is(err, sql.ErrNoRows) {
					return err
				}
				fresh, err := s.recordEvent(tx, id, "StrategyAccepted", body)
				if err != nil {
					return err
				}
				if fresh {
					if err := s.commitAccountEvent(tx, id, decimal.Zero, nil); err != nil {
						return err
					}
				}
			}
			return nil
		})
	})
}

func (s *Store) StrategyTotals(ctx context.Context, strategy StrategyID) (StrategyTotals, error) {
	var totals StrategyTotals
	err := s.commit(ctx, func(tx *storeTxn) error {
		var fee, funding string
		if err := tx.QueryRow(opReadStrategyTotals, s.accountID, string(strategy)).Scan(&fee, &funding); err != nil {
			return err
		}
		var err error
		totals.Fees, err = decimal.NewFromString(fee)
		if err != nil {
			return err
		}
		totals.Funding, err = decimal.NewFromString(funding)
		return err
	})
	return totals, err
}

func (s *Store) LatestPlan(ctx context.Context) (Plan, error) {
	var plan Plan
	err := s.commit(ctx, func(tx *storeTxn) error {
		var body string
		if err := tx.QueryRow(opReadLatestPlan, s.accountID).Scan(&body); err != nil {
			return err
		}
		return json.Unmarshal([]byte(body), &plan)
	})
	return plan, err
}

func (s *Store) Intent(ctx context.Context, id VirtualIntentID) (EligibleIntent, error) {
	var intent EligibleIntent
	err := s.commit(ctx, func(tx *storeTxn) error {
		var body string
		if err := tx.QueryRow(opReadIntentRuntime, s.accountID, string(id)).Scan(&body); err != nil {
			return err
		}
		if err := json.Unmarshal([]byte(body), &intent); err != nil {
			return err
		}
		if err := tx.QueryRow(opReadIntentFilled, s.accountID, string(id), s.accountID, string(id)).Scan(&intent.FilledSteps); err != nil {
			return err
		}
		if err := tx.QueryRow(opReadIntentReserved, s.accountID, string(id)).Scan(&intent.ReservedSteps); err != nil {
			return err
		}
		if intent.FilledSteps > intent.QuantitySteps {
			return errors.New("execution: late fills exceeded virtual intent; reconciliation required")
		}
		if intent.FilledSteps == intent.QuantitySteps {
			intent.State = Filled
		} else if intent.State != Canceled && intent.State != Expired {
			if intent.FilledSteps > 0 {
				intent.State = Partial
			} else if intent.ReservedSteps > 0 {
				intent.State = Reserved
			}
		}
		return nil
	})
	return intent, err
}

// EvaluateIntent checkpoints only trigger/expiry state. Fill and reservation
// highwaters remain derived from immutable allocation records.
func (s *Store) EvaluateIntent(ctx context.Context, id VirtualIntentID, observation ExecutionObservation, nowMS int64) (EligibleIntent, int64, error) {
	var intent EligibleIntent
	var available int64
	if observation.AtMS < 0 || observation.AtMS > nowMS || observation.ValidUntilMS <= nowMS {
		return intent, 0, errors.New("execution: invisible/expired intent observation")
	}
	err := s.commit(ctx, func(tx *storeTxn) error {
		var body string
		if err := tx.QueryRow(opReadIntentRuntime, s.accountID, string(id)).Scan(&body); err != nil {
			return err
		}
		if err := json.Unmarshal([]byte(body), &intent); err != nil {
			return err
		}
		var err error
		available, err = intent.Evaluate(observation.Price, nowMS, observation.Bar)
		if err != nil {
			return err
		}
		body, err = payload(intent)
		if err != nil {
			return err
		}
		if _, err := tx.Exec(opUpdateIntentRuntime, body, s.accountID, string(id)); err != nil {
			return err
		}
		var consumed int64
		if err := tx.QueryRow(opReadIntentConsumed, s.accountID, string(id), s.accountID, string(id)).Scan(&consumed); err != nil {
			return err
		}
		available = max(0, available-consumed)
		return nil
	})
	return intent, available, err
}

func (s *Store) Lot(ctx context.Context, strategy StrategyID, id VirtualLotID) (VirtualLot, error) {
	var lot VirtualLot
	err := s.commit(ctx, func(tx *storeTxn) error {
		var body string
		if err := tx.QueryRow(opReadLot, s.accountID, string(strategy), string(id)).Scan(&body); err != nil {
			return err
		}
		return json.Unmarshal([]byte(body), &lot)
	})
	return lot, err
}

func (s *Store) StrategyCheckpoint(ctx context.Context, strategy StrategyID, name string) (json.RawMessage, error) {
	if !canonicalID(string(strategy)) || !canonicalID(name) {
		return nil, errors.New("execution: invalid strategy checkpoint identity")
	}
	var body string
	err := s.commit(ctx, func(tx *storeTxn) error {
		return tx.QueryRow(opReadStrategyCheckpoint, s.accountID, string(strategy), name).Scan(&body)
	})
	return json.RawMessage(body), err
}
func (s *Store) SaveStrategyCheckpoint(ctx context.Context, strategy StrategyID, name string, body json.RawMessage) error {
	if strategy == "account-risk" && name == "policy-v1" {
		return errors.New("execution: account policy requires immutable registration")
	}
	if !canonicalID(string(strategy)) || !canonicalID(name) || !json.Valid(body) {
		return errors.New("execution: invalid strategy checkpoint")
	}
	return s.commit(ctx, func(tx *storeTxn) error {
		_, err := tx.Exec(opPutStrategyCheckpoint, s.accountID, string(strategy), name, string(body))
		return err
	})
}
