// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package orm

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
	CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error)
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

type dbBeginner interface {
	Begin(context.Context) (pgx.Tx, error)
}

func (q *Queries) begin(ctx context.Context) (pgx.Tx, *Queries, error) {
	beginner, ok := q.db.(dbBeginner)
	if !ok {
		return nil, nil, fmt.Errorf("database connection does not support transactions")
	}
	tx, err := beginner.Begin(ctx)
	if err != nil {
		return nil, nil, err
	}
	return tx, q.WithTx(tx), nil
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
